export type UiLanguage = "zh-CN" | "en-US";

const messages = {
  "zh-CN": {
    input: "输入内容", paste: "粘贴文本、需求或提示词…", readClipboard: "读取剪贴板", template: "模板", batch: "批量处理", adjust: "调整", optimize: "优化文本", generating: "正在生成", completed: "优化完成", failed: "生成失败", copy: "复制结果", retry: "重试", settings: "设置", current: "当前方案", analyzing: "正在分析场景", connecting: "正在连接模型", streaming: "正在生成内容", cancel: "取消", cancelGeneration: "取消生成", noProvider: "模型服务暂时不可用", openSettings: "打开设置", copied: "已复制到剪贴板"
  },
  "en-US": {
    input: "Input", paste: "Paste text, requirements, or a prompt...", readClipboard: "Read clipboard", template: "Templates", batch: "Batch", adjust: "Adjust", optimize: "Optimize text", generating: "Generating", completed: "Complete", failed: "Generation failed", copy: "Copy result", retry: "Retry", settings: "Settings", current: "Current setup", analyzing: "Analyzing scene", connecting: "Connecting model", streaming: "Generating content", cancel: "Cancel", cancelGeneration: "Cancel generation", noProvider: "The model service is unavailable", openSettings: "Open settings", copied: "Copied to clipboard"
  }
} as const;

const translations: Record<string, string> = {
  "取消": "Cancel", "取消生成": "Cancel generation", "重试": "Retry", "中文": "Chinese", "正在保存": "Saving", "✓ 源码已复制": "Source copied", "写一封商务邮件\n解释什么是机器学习": "Write a business email\nExplain machine learning", "通义千问": "Qwen", "智谱 GLM": "Zhipu GLM", "M2.7 高速版": "M2.7 Highspeed", "调整生成方案": "Adjust generation", "仅影响下一次生成": "Applies to the next run only", "尚未输入内容": "No input yet",
  "清空输入": "Clear input", "导出 Markdown": "Export Markdown", "结果已导出为 Markdown": "Result exported as Markdown",
  "导入文件": "Import file", "下载模板": "Download template", "已从 {name} 导入 {count} 条提示词": "Imported {count} prompts from {name}", "请选择 CSV 或 TXT 文件。": "Select a CSV or TXT file.", "文件超过 200 万字符限制。": "The file exceeds the 2 million character limit.", "文件中没有可导入的内容。": "The file has no importable content.", "无法读取该文件，请重试。": "The file could not be read. Try again.",
  "对比原文": "Compare original", "结果对比": "Result comparison", "关闭结果对比": "Close result comparison", "优化结果": "Optimized result", "原文已复制": "Original copied", "优化结果已复制": "Optimized result copied", "当前结果没有可用原文": "This result has no original text available",
  "界面主题": "Appearance", "跟随系统": "System", "浅色": "Light", "深色": "Dark",
  "内容优化": "Content optimization", "提示词生成": "Prompt generation", "简洁": "Concise", "平衡": "Balanced", "详细": "Detailed", "创意": "Creative", "精准": "Precise",
  "启动时读取": "Read on startup", "仅手动读取": "Read manually", "生成后自动替换": "Replace after generation", "自动": "Auto", "每次询问": "Ask every time", "手动固定": "Manual", "隐藏敏感内容": "Redact sensitive content", "保留原文": "Keep original text",
  "翻译": "Translate", "跨语言转换": "Cross-language conversion", "Markdown 预览": "Markdown preview", "渲染 Markdown 内容": "Render Markdown content", "批量处理": "Batch processing", "导入与导出批量提示词": "Import and export prompt batches", "语义识别": "Semantic detection", "使用已安装的本地模型增强场景识别": "Use installed local models to improve scene detection",
  "模型与 Provider": "Models & providers", "默认行为": "Defaults", "剪贴板": "Clipboard", "安全与隐私": "Security & privacy", "插件": "Plugins", "分栏": "Split", "源码": "Source", "预览": "Preview", "简体中文": "Simplified Chinese", "TXT 每行一条": "TXT: one prompt per line", "CSV prompt 列": "CSV: prompt column",
  "已启用。仅在优化时检查已安装的本地模型；模型不可用时自动回退通用场景。": "Enabled. Checks installed local models only during optimization; falls back to the general scene when unavailable.", "未启用。启用后只检查本地已安装模型，不会自动下载。": "Disabled. When enabled, only installed local models are checked; nothing is downloaded automatically.",
  "桌面入口暂不可用。": "Desktop controls are unavailable.", "当前环境无法保存设置。": "Settings cannot be saved in this environment.", "✓ 设置已保存": "Settings saved", "设置加载失败，请重试。": "Settings could not be loaded. Please retry.", "密钥状态读取失败，请重试。": "Key status could not be loaded. Please retry.", "快捷键状态暂不可用。": "Hotkey status is unavailable.", "当前环境无法保存密钥。": "Keys cannot be saved in this environment.", "请输入 API Key。": "Enter an API key.", "密钥已安全保存。": "Key saved securely.", "密钥保存失败，请重试。": "Key could not be saved. Please retry.", "删除已保存的 API Key？": "Delete the saved API key?", "当前环境无法删除密钥。": "Keys cannot be deleted in this environment.", "密钥已删除。": "Key deleted.", "密钥删除失败，请重试。": "Key could not be deleted. Please retry.",
  "✓ 已复制到剪贴板": "Copied to clipboard", "✓ 译文已复制": "Translation copied", "已设为当前结果": "Set as current result", "翻译暂时不可用，请重试。": "Translation is unavailable. Please retry.", "模板暂时无法保存，请重试。": "Template could not be saved. Please retry.", "请填写名称、分类和模板内容。": "Enter a name, category, and template content.", "模板已保存。": "Template saved.", "删除当前模板？": "Delete the current template?", "模板已删除。": "Template deleted.", "请填写全部变量后再应用。": "Fill in every variable before applying.", "模板已应用到输入区": "Template applied to the input.",
  "批处理暂时不可用，请重试。": "Batch processing is unavailable. Please retry.", "导入内容格式不正确，请检查后重试。": "The import format is invalid. Check it and retry.", "此条处理失败，请稍后重试。": "This item failed. Please retry later.", "导出暂时不可用，请重试。": "Export is unavailable. Please retry.", "批处理结果已导出": "Batch results exported", "评分未保存，请稍后重试。": "Rating was not saved. Please retry.", "评分已保存": "Rating saved", "历史记录暂时不可用。": "History is unavailable.",
  "Markdown 预览暂时不可用，请重试。": "Markdown preview is unavailable. Please retry.", "翻译结果不可用，请重试。": "Translation result is unavailable. Please retry.", "请先在设置中配置当前 Provider。": "Configure the current provider in Settings first.", "Provider 认证失败，请检查 API Key。": "Provider authentication failed. Check the API key.", "Provider 请求较多，请稍后重试。": "The provider is busy. Please retry later.", "模型服务响应超时，请重试。": "The model service timed out. Please retry.", "翻译功能已关闭，可在设置中重新启用。": "Translation is disabled. Re-enable it in Settings.", "模型没有返回可用译文，请重试。": "The model returned no usable translation. Please retry.",
  "已保存到本机": "Saved locally", "隐私模式": "Private mode", "正在保存": "Saving", "未保存": "Not saved", "已配置": "Configured", "未配置": "Not configured", "检查中": "Checking", "暂不可用": "Unavailable", "Provider：{provider}，{status}": "Provider: {provider}, {status}", "✓ 已替换剪贴板": "Clipboard replaced", "✓ 诊断 ID 已复制": "Diagnostic ID copied", "本次已替换，下次使用时仍会再次确认。": "Replaced this time. Confirmation will be requested again next time.",
  "生成设置": "Generation settings", "模式": "Mode", "风格": "Style", "场景": "Scene", "自动识别": "Auto detect", "模型": "Model", "当前输入": "Current input", "应用": "Apply", "更多操作": "More actions", "结果操作": "Result actions", "替换剪贴板": "Replace clipboard", "重新生成": "Regenerate", "模板管理": "Template manager", "评分": "Rating", "查看历史": "View history", "可以稍后重试，或检查当前 Provider 设置。": "Retry later or check the current provider settings.", "请检查文本或设置后再试。": "Check the text or settings and retry.", "复制诊断 ID": "Copy diagnostic ID", "错误信息已脱敏": "Error details are redacted", "错误代码：{code}": "Error code: {code}", "约 {count} 字": "About {count} characters", "{count} 字": "{count} characters",
  "读取剪贴板": "Read clipboard", "读取系统剪贴板内容到输入框": "Read the system clipboard into the input", "读取中…": "Reading...", "清空": "Clear", "清空输入": "Clear input", "清空当前输入": "Clear current input", "输入文本并开始优化，结果会在这里流式显示。": "Enter text and start optimizing; the result will stream here.", "正在与模型服务通信，请稍候。": "Communicating with the model service. Please wait.", "还没有结果": "No result yet", "没有可显示的结果": "No result to display", "请重新运行，或调整生成方案后再试。": "Run it again or adjust the generation settings.", "结果": "Result", "结果操作": "Result actions", "识别场景": "Detected scene", "翻译结果": "Translate result", "Markdown 预览": "Markdown preview", "对比原文": "Compare original", "对比": "Compare", "生成失败": "Generation failed", "打开设置": "Open settings", "已取消生成": "Generation cancelled", "本次没有生成内容，可以重新运行。": "No content was generated. You can run it again.", "重新生成": "Regenerate", "复制结果": "Copy result", "已复制": "Copied", "替换剪贴板": "Replace clipboard", "导出": "Export", "历史": "History", "结果反馈": "Result feedback", "结果满意": "Helpful result", "结果不满意": "Result needs improvement", "结果评分": "Result rating", "调整方案": "Adjust", "调整生成方案": "Adjust generation", "本次生成配置": "Generation settings", "本次生成": "This run", "配置摘要": "Configuration summary", "准备优化": "Ready to optimize", "正在生成…": "Generating...", "请重新输入文本后再试。": "Enter the text again and retry.", "你的输入已保留，请调整设置后再试。": "Your input is preserved. Adjust the settings and retry.", "你的输入已保留，请修改内容后再试。": "Your input is preserved. Edit the content and retry.", "你的输入已保留，请重新打开应用后再试。": "Your input is preserved. Reopen the app and retry.", "你的输入已保留，可稍后重试。": "Your input is preserved. Retry later.",
  "开始使用 Reflex": "Get started with Reflex", "先选择本次文本的处理方式。": "Choose how this text should be processed.", "接入方式": "Access method", "使用免费试用": "Use free trial", "通过 Reflex Cloud 处理，可查看剩余额度。": "Process through Reflex Cloud and view the remaining quota.", "使用自己的 API Key": "Use your own API key", "密钥只保存在 Windows 凭据管理器。": "Your key is stored only in Windows Credential Manager.", "已准备好": "Ready", "当前将使用 {provider}。": "This run will use {provider}.", "开始处理第一段文本": "Process your first text", "请先配置 API Key": "Configure an API key first", "免费试用暂不可用，请选择自备 API Key。": "The free trial is unavailable. Use your own API key instead.", "稍后设置": "Set up later", "常用任务": "Quick tasks", "优化表达": "Polish writing", "让文字更清楚、自然": "Make writing clearer and more natural", "压缩成摘要": "Summarize", "保留重点，减少冗余": "Keep the key points and cut repetition", "整理会议纪要": "Organize meeting notes", "提炼决策与行动项": "Extract decisions and action items", "更多工具": "More tools", "更多结果工具": "More result tools", "再调整": "Adjust again", "评分 {score}": "Rate {score}", "满意": "Helpful", "不满意": "Needs improvement",
  "自定义模板仅保存在本机配置中。": "Custom templates are stored only in local configuration.", "关闭模板管理": "Close template manager", "搜索模板": "Search templates", "搜索名称、分类或标签": "Search name, category, or tags", "模板分类": "Template category", "全部分类": "All categories", "新建模板": "New template", "还没有符合条件的模板。": "No matching templates yet.", "名称": "Name", "分类": "Category", "标签（用逗号分隔）": "Tags (comma-separated)", "说明": "Description", "模板内容": "Template content", "使用 {变量名} 插入需要填写的内容": "Use {variable} for values to fill in", "填写变量": "Fill variables", "删除": "Delete", "保存模板": "Save template", "应用到输入区": "Apply to input",
  "最多导入 200 条提示词，结果在本机导出。": "Import up to 200 prompts and export results locally.", "关闭批量处理": "Close batch processing", "导入格式": "Import format", "处理风格": "Processing style", "并发数": "Concurrency", "粘贴 CSV，需包含 prompt 或 提示词 列": "Paste CSV with a prompt column", "粘贴文本，每行一条提示词": "Paste text, one prompt per line", "批量输入内容": "Batch input", "正在解析": "Parsing", "解析内容": "Parse content", "正在处理 {processed}/{total}，已完成 {completed} 条": "Processing {processed}/{total}, {completed} complete", "已完成 {completed}/{total} 条": "Completed {completed}/{total}", "已停止，已完成 {completed} 条": "Stopped, {completed} complete", "已解析 {count} 条提示词": "Parsed {count} prompts", "等待导入内容": "Waiting for import content", "批处理列表": "Batch list", "等待": "Pending", "处理中": "Processing", "已完成": "Completed", "已停止": "Stopped", "失败": "Failed", "解析后将在这里显示待处理的提示词。": "Prompts ready to process will appear here after parsing.", "停止": "Stop", "导出结果": "Export results", "开始处理": "Start processing",
  "翻译结果": "Translation", "关闭翻译": "Close translation", "目标语言": "Target language", "原文": "Original", "译文": "Translation", "翻译已取消。": "Translation cancelled.", "正在翻译…": "Translating...", "准备翻译": "Ready to translate", "取消翻译": "Cancel translation", "重新翻译": "Translate again", "复制译文": "Copy translation", "作为当前结果": "Use as current result",
  "关闭 Markdown 预览": "Close Markdown preview", "预览方式": "Preview mode", "复制源码": "Copy source", "Markdown 源码": "Markdown source", "渲染预览": "Rendered preview", "正在渲染…": "Rendering...", "关闭": "Close", "替换剪贴板确认": "Clipboard replacement confirmation", "替换当前剪贴板内容？": "Replace the current clipboard content?", "原剪贴板内容会被本次结果覆盖。首次使用需要确认，之后可在设置中修改。": "This result will replace the current clipboard. The first use requires confirmation; change this later in Settings.", "确认替换": "Replace",
  "查看当前可用能力及其访问范围。": "Review available capabilities and their access scope.", "关闭插件": "Close plugins", "MiniMax 模型服务": "MiniMax model service", "生成与优化文本": "Generate and optimize text", "网络访问": "Network access", "内置模板": "Built-in templates", "提供场景、风格与语言模板": "Provides scene, style, and language templates", "本地内容": "Local content", "场景识别": "Scene detection", "根据当前文本选择适合的处理方式": "Selects a suitable workflow from the current text", "本地文本": "Local text", "3 项内置能力": "3 built-in capabilities", "管理设置": "Manage settings",
  "本地语义模型": "Local semantic model", "模型下载进度": "Model download progress", "检查状态": "Check status", "取消下载": "Cancel download", "删除模型": "Delete model", "下载模型": "Download model", "删除本地语义模型？之后仍可重新下载。": "Delete the local semantic model? You can download it again later.", "保存设置后即可管理本地模型。": "Save settings to manage the local model.", "正在检查本地模型…": "Checking the local model...", "正在下载 {percent}%": "Downloading {percent}%", "正在删除本地模型…": "Deleting the local model...", "模型已就绪 · {size}": "Model ready · {size}", "尚未下载本地语义模型。": "The local semantic model has not been downloaded.", "本地语义运行组件尚未安装。": "The local semantic runtime is not installed.", "缺少本地模型下载组件。": "The local model download component is missing.", "模型下载失败，请检查网络后重试。": "Model download failed. Check the network and retry.", "模型文件不完整，请重新下载。": "The model files are incomplete. Download them again.", "本地模型删除失败。": "The local model could not be deleted.", "本地模型状态暂时不可用。": "The local model status is temporarily unavailable.", "检查本地模型后可启用更准确的场景识别。": "Check the local model to enable more accurate scene detection.",
  "参与匿名质量分析": "Share anonymous quality metrics", "仅记录质量发布版本与反馈结果，不包含输入或输出正文，默认关闭": "Records only the quality-release version and feedback outcome, without input or output text. Off by default.", "加入产品改进计划": "Join the product improvement program", "仅在开启后保留脱敏的云端输入和结果，默认关闭": "Stores redacted cloud inputs and results only when enabled. Off by default.", "云端隐私设置已更新。": "Cloud privacy settings updated.", "当前质量发布：{version} · {title}": "Current quality release: {version} · {title}", "当前尚无已发布的质量改进。": "No quality improvement release is currently published.",
  "管理模型、默认行为和本地隐私。": "Manage models, defaults, and local privacy.", "关闭设置": "Close settings", "设置分类": "Settings categories", "默认 Provider": "Default provider", "默认模型": "Default model", "输入新的 API Key": "Enter a new API key", "保存密钥": "Save key", "删除密钥": "Delete key", "密钥只保存在系统安全存储中，输入不会保留。": "Keys are stored only in the system secure store; input is not retained.", "密钥已保存": "Key saved", "尚未配置密钥": "No key configured", "尾号 {tail}": "Ending in {tail}", "保存后即可使用当前 Provider": "Save a key to use the current provider", "默认模式": "Default mode", "默认风格": "Default style", "场景识别策略": "Scene detection policy", "界面与输出语言": "Interface & output language", "全局快捷键": "Global hotkey", "当前快捷键已启用": "Current hotkey is enabled", "保存后启用快捷键": "Save to enable the hotkey", "读取与替换策略": "Read & replace policy", "自动替换会覆盖当前剪贴板内容，首次使用仍需确认。": "Automatic replacement overwrites the clipboard; the first use still needs confirmation.", "保存历史记录": "Save history", "记录优化结果，便于稍后查看": "Keep optimization results for later review", "隐私模式": "Privacy mode", "减少本地内容保留": "Reduce locally retained content", "历史内容处理": "History content handling", "保存设置": "Save settings", "本地诊断包": "Local diagnostic bundle", "仅导出脱敏的本地运行信息，不包含输入正文或密钥。": "Exports only redacted local runtime information, without input content or credentials.", "导出诊断包": "Export diagnostic bundle", "取消导出": "Cancel export", "当前环境无法导出诊断包。": "Diagnostic export is unavailable in this environment.", "正在导出诊断包...": "Exporting diagnostic bundle...", "诊断包已导出。": "Diagnostic bundle exported.", "诊断包导出已取消。": "Diagnostic export cancelled.", "正在取消诊断包导出...": "Cancelling diagnostic export...", "诊断包导出失败，请重试。": "Diagnostic export failed. Try again.",
  "暂无可导出的诊断记录。请先启用本地诊断。": "No diagnostic records are available. Enable local diagnostics first.", "诊断记录包含无法安全导出的内容，已停止导出。": "Export stopped because the diagnostic records contain content that cannot be exported safely.", "诊断包正在导出，请稍候。": "A diagnostic bundle is already being exported. Please wait.",
  "输入内容无效，请检查后重试。": "The input is invalid. Check it and try again.", "生成方案准备失败，请稍后重试。": "The generation plan could not be prepared. Try again later.", "模型没有返回可用内容，请重试。": "The model returned no usable content. Try again.", "模型输出超过允许长度，请缩短输入后重试。": "The model output exceeded the allowed length. Shorten the input and try again.", "模型响应超时，请稍后重试。": "The model response timed out. Try again later.", "模型服务返回了无效结果，请重试。": "The model service returned an invalid result. Try again.", "模型服务网络连接失败，请重试。": "The model service could not be reached. Try again.", "模型服务请求失败，请稍后重试。": "The model service request failed. Try again later.",
  "云端服务暂不可用，请稍后重试。": "The cloud service is temporarily unavailable. Try again later.", "请求内容无效，请检查后重试。": "The request is invalid. Check it and try again.", "安装身份已失效，请重新打开应用。": "This installation session has expired. Reopen the app.", "今日免费额度已用完，可明天再试或使用自备 Provider。": "Today's free quota is exhausted. Try again tomorrow or use your own provider.", "输入内容过长，请缩短后重试。": "The input is too long. Shorten it and try again.", "免费额度服务暂时不可用，请稍后再试。": "The free quota service is temporarily unavailable. Try again later.", "当前网络请求过于频繁，请稍后再试。": "Requests from this network are too frequent. Try again later.", "网络限流服务暂时不可用，请稍后再试。": "The network rate-limit service is temporarily unavailable. Try again later.",
  "今日云端请求额度已用完，请明天再试或切换到自备 Provider。": "Today's cloud request budget is exhausted. Try again tomorrow or switch to your own provider.", "今日云端服务预算已用完，请稍后再试或切换到自备 Provider。": "Today's cloud service budget is exhausted. Try again later or switch to your own provider.", "云端计费配置暂不可用，请稍后再试。": "Cloud pricing configuration is temporarily unavailable. Try again later.", "云端预算服务暂时不可用，请稍后再试。": "The cloud budget service is temporarily unavailable. Try again later.", "云端 Provider 尚未配置，请改用自备 Provider 或联系管理员。": "The cloud provider is not configured. Use your own provider or contact the administrator.", "云端当前繁忙，请稍后重试。": "The cloud service is busy. Try again later.", "当前安装已有请求处理中，请等待完成。": "This installation already has a request in progress. Wait for it to finish.", "该请求正在处理中，请勿重复提交。": "This request is already being processed. Do not submit it again.",
  "请先在隐私设置中开启对应的数据改进授权。": "Enable the corresponding data-improvement consent in Privacy settings first.", "隐私授权版本已更新，请刷新授权设置后再提交。": "The privacy consent version has changed. Refresh your consent settings and submit again.", "云端免费额度已用完或请求过于频繁。": "The cloud free quota is exhausted or requests are too frequent.", "云端服务返回了无效数据。": "The cloud service returned invalid data.",
  "内容与沟通": "Content & communication", "软件研发": "Software development", "研究与分析": "Research & analysis", "学习与教学": "Learning & teaching", "工作与决策": "Work & decisions", "创意叙事": "Creative storytelling", "翻译与本地化": "Translation & localization", "问题解决与风险": "Problem solving & risk",
  "结构、表达和读者吸引力": "Structure, clarity, and reader appeal", "平台语气和传播效率": "Platform tone and reach", "语气、目标和行动项": "Tone, objective, and actions", "卖点、记忆点和行动号召": "Value proposition, memorability, and call to action", "价值、特性和使用场景": "Value, features, and use cases", "论点、证据和学术表达": "Claims, evidence, and academic style",
  "需求到实现提示词": "Requirements-to-implementation prompts", "风险、缺陷和修复建议": "Risks, defects, and fixes", "复现、根因和验证": "Reproduction, root cause, and verification", "保持行为并改善结构": "Preserve behavior while improving structure", "接口、示例和失败行为": "Interfaces, examples, and failure behavior",
  "指标、方法和结论": "Metrics, methods, and conclusions", "市场、用户和证据": "Market, users, and evidence", "差异、优势和风险": "Differentiation, strengths, and risks", "研究脉络和证据缺口": "Research landscape and evidence gaps", "信号、假设和不确定性": "Signals, assumptions, and uncertainty",
  "概念、示例和理解路径": "Concepts, examples, and learning path", "目标、节奏和复盘": "Goals, pace, and review", "考纲、练习和时间安排": "Syllabus, practice, and schedule", "目标、活动和评价": "Objectives, activities, and assessment", "思路、步骤和检查": "Reasoning, steps, and checks",
  "结论、依据和格式": "Conclusions, evidence, and format", "选项、权衡和建议": "Options, trade-offs, and recommendations", "范围、里程碑和依赖": "Scope, milestones, and dependencies", "步骤、控制和指标": "Steps, controls, and metrics", "决策、行动和负责人": "Decisions, actions, and owners",
  "人物、冲突和节奏": "Characters, conflict, and pacing", "场景、对白和镜头": "Scenes, dialogue, and shots", "意象、节奏和语言": "Imagery, rhythm, and language", "任务、冲突和反馈": "Quests, conflict, and feedback", "规则、历史和一致性": "Rules, history, and consistency",
  "保留结构与术语": "Preserve structure and terminology", "文化、界面和语境": "Culture, interface, and context", "风格、语义和韵律": "Style, meaning, and cadence", "术语表和一致性": "Glossary and consistency", "信息压缩和可读性": "Information compression and readability",
  "事实、假设和下一步": "Facts, hypotheses, and next steps", "选项、步骤和可行性": "Options, steps, and feasibility", "证据链和系统原因": "Evidence chain and systemic causes", "概率、影响和缓解": "Likelihood, impact, and mitigation", "触发、响应和恢复": "Triggers, response, and recovery",
  "选择本次场景": "Choose a scene for this run", "搜索场景": "Search scenes", "场景分类": "Scene category", "由本地场景路由选择": "Selected by the local scene router", "没有匹配的场景": "No matching scenes", "已显示 {count} 个场景": "Showing {count} scenes", "当前场景：{scene}": "Current scene: {scene}", "开始生成": "Generate",
  "主动反馈询问": "Proactive feedback prompts", "在若干次成功生成后偶尔询问结果是否有帮助": "Occasionally ask whether a result was helpful after several successful runs", "这次结果有帮助吗？": "Was this result helpful?", "你的选择会帮助我们改进场景和模型效果，不会附带输入或结果。": "Your response helps improve scene routing and model quality. No input or result is attached.",
  "稍后反馈": "Respond later", "稍后": "Later", "有帮助": "Helpful", "需要改进": "Needs improvement", "正在记录": "Saving", "稍后再问": "Ask me later", "不再主动询问": "Do not ask again", "反馈已记录，谢谢。": "Feedback recorded. Thank you.", "已关闭主动反馈询问": "Proactive feedback prompts disabled",
  "关闭反馈": "Close feedback", "结果不满意": "Result needs improvement", "结果满意": "Helpful result", "提交反馈": "Send feedback", "反馈类型": "Feedback type", "结果质量": "Result quality", "功能异常": "Bug", "速度与性能": "Speed & performance", "功能建议": "Feature request", "其他": "Other",
  "具体问题": "Details", "描述发生了什么…": "Describe what happened...", "期望结果": "Expected result", "你希望得到怎样的结果？": "What result did you expect?", "联系方式（可选）": "Contact (optional)", "邮箱或其他联系方式": "Email or another contact method", "应用截图预览": "App screenshot preview", "移除截图": "Remove screenshot", "即将随反馈提交的 Reflex 应用截图": "Reflex app screenshot to be attached", "未附加截图": "No screenshot attached",
  "附加本次输入": "Attach this input", "附加本次结果": "Attach this result", "附加应用截图": "Attach app screenshot", "附加输入和结果前，请先在设置的安全与隐私中开启产品改进计划。": "Enable the product improvement program in Security & privacy before attaching input or results.", "仅勾选的内容会随反馈发送。": "Only selected content will be sent.", "API Key 和无关剪贴板内容不会上传。": "API keys and unrelated clipboard content are never uploaded.", "正在发送": "Sending", "发送反馈": "Send feedback",
  "窗口截图失败，可以不附加截图继续反馈。": "The window screenshot failed. You can continue without it.", "当前环境无法截取应用窗口。": "This environment cannot capture the app window.", "反馈已发送，谢谢。": "Feedback sent. Thank you.", "反馈发送失败，请稍后重试。": "Feedback could not be sent. Try again later.", "反馈服务暂不可用，请稍后重试。": "Feedback is temporarily unavailable. Try again later.", "反馈服务返回了无效结果。": "The feedback service returned an invalid result.",
  "请先在设置中开启对应的隐私授权。": "Enable the corresponding privacy consent in Settings first.", "隐私授权已更新，请刷新设置后重新提交。": "Privacy consent has changed. Refresh Settings and submit again.", "反馈提交过于频繁，请稍后再试。": "Feedback is being submitted too frequently. Try again later.", "反馈内容不完整，请检查后重试。": "The feedback is incomplete. Check it and try again.", "反馈附件暂时无法保存，请稍后再试。": "The feedback attachment cannot be saved right now. Try again later.",
  "（实验）": "(Experimental)", "此 Provider 仍在实验支持阶段，协议或模型可用性可能变化。": "This provider is still experimental; protocol or model availability may change.",
  "通用": "General", "默认回退场景": "Default fallback scene", "文章写作": "Article writing", "社媒文案": "Social media", "邮件": "Email", "广告创意": "Ad creative", "产品描述": "Product description", "论文写作": "Academic writing", "代码生成": "Code generation", "代码审查": "Code review", "Bug 修复": "Bug fix", "代码重构": "Code refactoring", "技术文档": "Technical documentation", "数据分析": "Data analysis", "市场调研": "Market research", "竞品分析": "Competitor analysis", "文献综述": "Literature review", "趋势预测": "Trend forecasting", "知识讲解": "Knowledge explanation", "学习计划": "Study plan", "考试备考": "Exam preparation", "课程设计": "Course design", "作业辅导": "Homework help", "报告写作": "Report writing", "决策分析": "Decision analysis", "项目规划": "Project planning", "流程优化": "Process optimization", "会议纪要": "Meeting summary", "故事创作": "Story writing", "剧本创作": "Script writing", "诗歌创作": "Poetry", "游戏剧情": "Game narrative", "世界观构建": "World building", "文档翻译": "Document translation", "本地化适配": "Localization", "文学翻译": "Literary translation", "术语统一": "Terminology", "口译笔记": "Interpreting notes", "问题诊断": "Problem diagnosis", "解决方案": "Solution design", "根因分析": "Root cause analysis", "风险评估": "Risk assessment", "应急预案": "Emergency plan"
  ,"历史记录": "History", "历史记录维护": "History maintenance", "维护": "Manage", "导出格式": "Export format", "导出历史记录": "Export history", "导出": "Export", "检查记录": "Check records", "修复历史记录": "Repair history", "修复": "Repair", "恢复备份": "Restore backup", "正在加载备份...": "Loading backups...", "备份列表暂时不可用": "Backups are unavailable", "暂无备份": "No backups", "重试加载备份": "Retry loading backups", "重试备份": "Retry backups", "恢复": "Restore", "轮换密钥": "Rotate key", "清空历史": "Clear history", "搜索历史记录": "Search history", "场景筛选": "Filter scene", "全部场景": "All scenes", "风格筛选": "Filter style", "全部风格": "All styles", "Provider 筛选": "Filter provider", "全部 Provider": "All providers", "筛选": "Filter", "历史记录列表": "History list", "正在加载历史记录...": "Loading history...", "暂无历史记录。": "No history yet.", "正在加载...": "Loading...", "加载更多": "Load more", "选择一条历史记录查看详情。": "Select a history item to view details.", "正在加载详情...": "Loading details...", "未评分": "Unrated", "删除当前历史记录": "Delete current history item", "耗时": "Elapsed", "结果": "Result", "载入原文": "Load original", "使用结果": "Use result", "历史记录未启用，请先在设置中开启。": "History is disabled. Enable it in Settings.", "历史记录暂时不可用，请稍后重试。": "History is unavailable. Please retry.", "评分已保存。": "Rating saved.", "评分未保存，请稍后重试。": "Rating was not saved. Please retry.", "请先选择要恢复的备份。": "Select a backup to restore first.", "正在处理历史记录...": "Processing history...", "历史操作已完成。": "History operation completed.", "历史操作失败，请稍后重试。": "History operation failed. Please retry.", "当前搜索条件暂不支持导出，请先清除搜索。": "Export is unavailable while searching. Clear the search first.", "正在导出历史记录...": "Exporting history...", "历史导出失败，请稍后重试。": "History export failed. Please retry.", "正在扫描历史记录...": "Checking history...", "历史记录检查失败，请稍后重试。": "History check failed. Please retry.", "已发送到主窗口。": "Sent to the main window.", "无法载入这条历史记录。": "This history item could not be loaded.",
  "删除后当前 Provider 将无法调用，之后仍可重新保存。": "The current provider will be unavailable until a new key is saved.", "删除后无法恢复，但不会影响已经生成的内容。": "This cannot be undone, but generated content will not be affected.", "删除模板": "Delete template", "删除本地语义模型？": "Delete the local semantic model?", "删除后场景识别会自动回退，之后仍可重新下载。": "Scene detection will fall back automatically. The model can be downloaded again later."
};

export type MessageKey = keyof (typeof messages)["zh-CN"];

export function t(language: UiLanguage, key: MessageKey): string {
  return messages[language][key];
}

export function translate(
  language: UiLanguage,
  source: string,
  values: Record<string, string | number> = {}
): string {
  const value = language === "en-US" ? (translations[source] ?? source) : source;
  return value.replace(/\{(\w+)\}/g, (match, key) => String(values[key] ?? match));
}
